services:
  elasticsearch:
    container_name: elasticsearch
    platform: linux/amd64
    image: elasticsearch:6.4.3
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=javacafe-cluster
      - node.name=javacafe-node1
      - node.master=true
      - node.data=true
      - discovery.type=single-node
      - bootstrap.system_call_filter=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    user: root
    restart: always
  kibana:
    container_name: kibana
    platform: linux/amd64
    image: kibana:6.4.3
    ports:
      - 5601:5601
    networks:
      - default
    environment:
      - "ELASTICSERCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - TZ=Asia/Seoul
    restart: always
    depends_on:
      - elasticsearch
networks:
  default:
    external:
      name: elastic