name: Simple custom action using go

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'release/**'

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KimDoubleB/go-action@v1.6
        with:
          health_check_url: ${{ secrets.PRD_HEALTH_URL }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
