name: Simple custom action using go

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'release/**'

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KimDoubleB/go-action@v1.1